### ISSUE TITLE
Image version is v0.0.0

### ISSUE THREAD

**Issue by anfechtung** [cert-manager/istio-csr#285]
A recent change set the `Chart.yaml` image version value to `v0.0.0` which does not align with an actual oci image tag:

```
appVersion: v0.0.0
version: v0.0.0
```

https://github.com/cert-manager/istio-csr/blob/main/deploy/charts/istio-csr/Chart.yaml#L26

This is causing our deployments to fail.

**Comment by anfechtung** [comment]
So the change to `v0.0.0` was deliberate to essentially prevent deployment from the GitRepo?  Unfortunately, the process I am using to deploy istio-csr requires me to use a Flux GitRepository as the source.

**Comment by inteon** [comment]
We changed the value because the version in the git repo will not match the latest version in the future.
We overwrite the value before we create the Helm chart and publish it, this simplifies the release process (does no longer require us to manually update these files).
The best solution would be to use Flux HelmRepository instead of Flux GitRepository.

**Comment by anfechtung** [comment]
Understood.  Thank you.  I will open an issue with product we are using to orchestrate our deployment, asking them to support HelmRepository.
