### ISSUE TITLE
Feature request: istio-ca-root-cert to use secret instead of configmap

### ISSUE THREAD

**Issue by c0ffeec0der** [cert-manager/istio-csr#49]
The current code store root cert in configmap, can istio-csr store the cert in secret?

**Comment by xUnholy** [comment]
@c0ffeec0der CAs are public, why do you want it to be a secret?

**Comment by c0ffeec0der** [comment]
@xUnholy 

Correct it is public. However, the nature of configmap as described in https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

is to decouple configuration

where secret as described in https://kubernetes.io/docs/concepts/configuration/secret/

is to store sensitive data

given than CA is more to data rather than config. It's better to store as secret, and it will be uniform with cert-manager which store cert as secret

**Comment by JoshVanL** [comment]
Storing the CA in a config-map is a constraint set by istio. This matches the behavior of Kubernetes itself which stores the API server CA in the ConfigMap `kube-root-ca.crt` in every namespace. 

Since there is nothing istio-csr can do about this I will close the issue. If this changes in future we can re-visit.

/close
